//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Resources.DashboardResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DashBoardResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DashBoardResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseManager.Resources.DashboardResources.DashBoardResource", typeof(DashBoardResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses by category in last month.
        /// </summary>
        public static string ExpensesByCategoryInLastMonth {
            get {
                return ResourceManager.GetString("ExpensesByCategoryInLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select filter criteria:.
        /// </summary>
        public static string FilterCriteriaDescription {
            get {
                return ResourceManager.GetString("FilterCriteriaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graph summaries.
        /// </summary>
        public static string GraphSummaries {
            get {
                return ResourceManager.GetString("GraphSummaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomes by category in last month.
        /// </summary>
        public static string IncomesByCategoryInLastMonth {
            get {
                return ResourceManager.GetString("IncomesByCategoryInLastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month report.
        /// </summary>
        public static string LastMonthReport {
            get {
                return ResourceManager.GetString("LastMonthReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} transactions..
        /// </summary>
        public static string LastXTransaction {
            get {
                return ResourceManager.GetString("LastXTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last year report.
        /// </summary>
        public static string LastYearReport {
            get {
                return ResourceManager.GetString("LastYearReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  ..
        /// </summary>
        public static string MonthDelimiter {
            get {
                return ResourceManager.GetString("MonthDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add some transactions so you can see your personal dashboard..
        /// </summary>
        public static string NoDataDescription {
            get {
                return ResourceManager.GetString("NoDataDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available  :(.
        /// </summary>
        public static string NoDataHeader {
            get {
                return ResourceManager.GetString("NoDataHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not enough data available..
        /// </summary>
        public static string NotEnoughDataAvailable {
            get {
                return ResourceManager.GetString("NotEnoughDataAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Expense manager - best money management application. You have to login to show more functionality..
        /// </summary>
        public static string WelcomeDescription {
            get {
                return ResourceManager.GetString("WelcomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello anonymous user!.
        /// </summary>
        public static string WelcomeHeader {
            get {
                return ResourceManager.GetString("WelcomeHeader", resourceCulture);
            }
        }
    }
}
