//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Resources.BudgetResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BudgetAccessRightResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BudgetAccessRightResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseManager.Resources.BudgetResources.BudgetAccessRightResource", typeof(BudgetAccessRightResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned user.
        /// </summary>
        public static string AssignedUser {
            get {
                return ResourceManager.GetString("AssignedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget access right management.
        /// </summary>
        public static string BudgetAccessRightManagement {
            get {
                return ResourceManager.GetString("BudgetAccessRightManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget wasn&apos;t found for given budget access right.
        /// </summary>
        public static string BudgetNotFoundById {
            get {
                return ResourceManager.GetString("BudgetNotFoundById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create budget access right.
        /// </summary>
        public static string CreateBudgetAccessRight {
            get {
                return ResourceManager.GetString("CreateBudgetAccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete budget access right.
        /// </summary>
        public static string DeleteBudgetAccessRight {
            get {
                return ResourceManager.GetString("DeleteBudgetAccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit budget access right.
        /// </summary>
        public static string EditBudgetAccessRight {
            get {
                return ResourceManager.GetString("EditBudgetAccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request for {0} was successfully sent. You must now wait until user accepts your budget invitation..
        /// </summary>
        public static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access right {0} for budget {1} was successfully granted!.
        /// </summary>
        public static string SuccessfullCreation {
            get {
                return ResourceManager.GetString("SuccessfullCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access right {0} for user {1} was successfully deleted!.
        /// </summary>
        public static string SuccessfullDelete {
            get {
                return ResourceManager.GetString("SuccessfullDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access right for user {0} was successfully edited!.
        /// </summary>
        public static string SuccessfullEdit {
            get {
                return ResourceManager.GetString("SuccessfullEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete access right {0} for user {1}?.
        /// </summary>
        public static string SureOfDelete {
            get {
                return ResourceManager.GetString("SureOfDelete", resourceCulture);
            }
        }
    }
}
