//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Resources.BudgetResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BudgetResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BudgetResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseManager.Resources.BudgetResources.BudgetResource", typeof(BudgetResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budgets management.
        /// </summary>
        public static string BudgetsManagement {
            get {
                return ResourceManager.GetString("BudgetsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create budget.
        /// </summary>
        public static string CreateBudget {
            get {
                return ResourceManager.GetString("CreateBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete budget.
        /// </summary>
        public static string DeleteBudget {
            get {
                return ResourceManager.GetString("DeleteBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit budget.
        /// </summary>
        public static string EditBudget {
            get {
                return ResourceManager.GetString("EditBudget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limit of budget has to be greater than 0!.
        /// </summary>
        public static string LimitGreaterThanZero {
            get {
                return ResourceManager.GetString("LimitGreaterThanZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of the budget can not be empty!.
        /// </summary>
        public static string NameNotNull {
            get {
                return ResourceManager.GetString("NameNotNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget {0} was successfully created!.
        /// </summary>
        public static string SuccessfullCreation {
            get {
                return ResourceManager.GetString("SuccessfullCreation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget {0} was successfully deleted!.
        /// </summary>
        public static string SuccessfullDelete {
            get {
                return ResourceManager.GetString("SuccessfullDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget {0} was successfully edited!.
        /// </summary>
        public static string SuccessfullEdit {
            get {
                return ResourceManager.GetString("SuccessfullEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete budget {0}?.
        /// </summary>
        public static string SureOfDelete {
            get {
                return ResourceManager.GetString("SureOfDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start date has to be before end date!.
        /// </summary>
        public static string WrongDateSpan {
            get {
                return ResourceManager.GetString("WrongDateSpan", resourceCulture);
            }
        }
    }
}
