//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Resources.TransactionResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TransactionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TransactionResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseManager.Resources.TransactionResources.TransactionResource", typeof(TransactionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new expense.
        /// </summary>
        public static string AddExpense {
            get {
                return ResourceManager.GetString("AddExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new income.
        /// </summary>
        public static string AddIncome {
            get {
                return ResourceManager.GetString("AddIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transaction amount must be greater than zero.
        /// </summary>
        public static string AmmountError {
            get {
                return ResourceManager.GetString("AmmountError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget name.
        /// </summary>
        public static string BudgetName {
            get {
                return ResourceManager.GetString("BudgetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Budget.
        /// </summary>
        public static string BudgetSelection {
            get {
                return ResourceManager.GetString("BudgetSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category field is required.
        /// </summary>
        public static string CategoryError {
            get {
                return ResourceManager.GetString("CategoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Category.
        /// </summary>
        public static string CategorySelection {
            get {
                return ResourceManager.GetString("CategorySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose type of transaction.
        /// </summary>
        public static string ChooseType {
            get {
                return ResourceManager.GetString("ChooseType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency field is required..
        /// </summary>
        public static string CurrencyError {
            get {
                return ResourceManager.GetString("CurrencyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Currency.
        /// </summary>
        public static string CurrencySelection {
            get {
                return ResourceManager.GetString("CurrencySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date was not in format dd.MM.yyyy.
        /// </summary>
        public static string DateError {
            get {
                return ResourceManager.GetString("DateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete transaction.
        /// </summary>
        public static string DeleteTransaction {
            get {
                return ResourceManager.GetString("DeleteTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit expense transaction.
        /// </summary>
        public static string EditExpense {
            get {
                return ResourceManager.GetString("EditExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit income transaction.
        /// </summary>
        public static string EditIncome {
            get {
                return ResourceManager.GetString("EditIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        public static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CSV file is damaged.
        /// </summary>
        public static string FileFormatError {
            get {
                return ResourceManager.GetString("FileFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency.
        /// </summary>
        public static string Frequency {
            get {
                return ResourceManager.GetString("Frequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Frequency.
        /// </summary>
        public static string FrequencySelection {
            get {
                return ResourceManager.GetString("FrequencySelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        public static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat transaction?.
        /// </summary>
        public static string IsRepeatable {
            get {
                return ResourceManager.GetString("IsRepeatable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat until.
        /// </summary>
        public static string LastOccurrence {
            get {
                return ResourceManager.GetString("LastOccurrence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date until which transaction should be repeated must be after first transaction occurrence.
        /// </summary>
        public static string LastOccurrenceBeforeDateError {
            get {
                return ResourceManager.GetString("LastOccurrenceBeforeDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of last occurrence must be set.
        /// </summary>
        public static string LastOccurrenceNullError {
            get {
                return ResourceManager.GetString("LastOccurrenceNullError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat every.
        /// </summary>
        public static string NextRepeat {
            get {
                return ResourceManager.GetString("NextRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequency must be positive number.
        /// </summary>
        public static string NextRepeatError {
            get {
                return ResourceManager.GetString("NextRepeatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transactions overview.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to view this wallet.
        /// </summary>
        public static string PermissionError {
            get {
                return ResourceManager.GetString("PermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to create transactions in this wallet.
        /// </summary>
        public static string PermissionErrorCreate {
            get {
                return ResourceManager.GetString("PermissionErrorCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to delete this transaction.
        /// </summary>
        public static string PermissionErrorDelete {
            get {
                return ResourceManager.GetString("PermissionErrorDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You don&apos;t have permission to edit this transaction.
        /// </summary>
        public static string PermissionErrorEdit {
            get {
                return ResourceManager.GetString("PermissionErrorEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WalletId must have set Id.
        /// </summary>
        public static string WalletIdError {
            get {
                return ResourceManager.GetString("WalletIdError", resourceCulture);
            }
        }
    }
}
