// <auto-generated />
namespace ExpenseManager.Database.Seeding.Context.SeedingContextMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RepeatableTransactionFixes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RepeatableTransactionFixes));
        
        string IMigrationMetadata.Id
        {
            get { return "201511141841591_RepeatableTransactionFixes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
