//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExpenseManager.Resources.WalletResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WalletAccessRightResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WalletAccessRightResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ExpenseManager.Resources.WalletResources.WalletAccessRightResource", typeof(WalletAccessRightResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned Permission.
        /// </summary>
        public static string AssignedPermission {
            get {
                return ResourceManager.GetString("AssignedPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned User Name.
        /// </summary>
        public static string AssignedUserName {
            get {
                return ResourceManager.GetString("AssignedUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create wallet access right.
        /// </summary>
        public static string CreateWalletAccessRight {
            get {
                return ResourceManager.GetString("CreateWalletAccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete wallet access right.
        /// </summary>
        public static string DeleteWalletAccessRight {
            get {
                return ResourceManager.GetString("DeleteWalletAccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit wallet access right.
        /// </summary>
        public static string EditWalletAccessRight {
            get {
                return ResourceManager.GetString("EditWalletAccessRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage wallet access rights.
        /// </summary>
        public static string ManageWalletAccessRights {
            get {
                return ResourceManager.GetString("ManageWalletAccessRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select permission.
        /// </summary>
        public static string SelectPermission {
            get {
                return ResourceManager.GetString("SelectPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
